"""Metrics tables

Revision ID: 7e5dea87e1d2
Revises: 
Create Date: 2024-11-05 16:23:08.509199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5dea87e1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('metric')
    )
    op.create_index(op.f('ix_metrics_metric'), 'metrics', ['metric'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_metric'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
